# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import apteco_api
from apteco_api.models.modify_items_modify_user_collection import ModifyItemsModifyUserCollection  # noqa: E501
from apteco_api.rest import ApiException


class TestModifyItemsModifyUserCollection(unittest.TestCase):
    """ModifyItemsModifyUserCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyItemsModifyUserCollection(self):
        """Test ModifyItemsModifyUserCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apteco_api.models.modify_items_modify_user_collection.ModifyItemsModifyUserCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
