# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import apteco_api
from apteco_api.models.data_view_details import DataViewDetails  # noqa: E501
from apteco_api.rest import ApiException


class TestDataViewDetails(unittest.TestCase):
    """DataViewDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataViewDetails(self):
        """Test DataViewDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apteco_api.models.data_view_details.DataViewDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
