# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import apteco_api
from apteco_api.models.text_variable_info import TextVariableInfo  # noqa: E501
from apteco_api.rest import ApiException


class TestTextVariableInfo(unittest.TestCase):
    """TextVariableInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextVariableInfo(self):
        """Test TextVariableInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apteco_api.models.text_variable_info.TextVariableInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
