# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import apteco_api
from apteco_api.api.fast_stats_jobs_api import FastStatsJobsApi  # noqa: E501
from apteco_api.rest import ApiException


class TestFastStatsJobsApi(unittest.TestCase):
    """FastStatsJobsApi unit test stubs"""

    def setUp(self):
        self.api = apteco_api.api.fast_stats_jobs_api.FastStatsJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fast_stats_jobs_calculate_processing_time_stats_for_system_sync(self):
        """Test case for fast_stats_jobs_calculate_processing_time_stats_for_system_sync

        EXPERIMENTAL: Requires OrbitAdmin: Calculate processing statistics for the specified jobs in the FastStats job queue for the given system.  # noqa: E501
        """
        pass

    def test_fast_stats_jobs_calculate_processing_time_stats_sync(self):
        """Test case for fast_stats_jobs_calculate_processing_time_stats_sync

        EXPERIMENTAL: Requires OrbitAdmin: Calculate processing statistics for the specified jobs in the FastStats job queue for all systems in a particular DataView.  # noqa: E501
        """
        pass

    def test_fast_stats_jobs_get_fast_stats_job(self):
        """Test case for fast_stats_jobs_get_fast_stats_job

        EXPERIMENTAL: Requires OrbitAdmin: Gets details for a particular job in the FastStats job queue for the given system.  # noqa: E501
        """
        pass

    def test_fast_stats_jobs_get_fast_stats_jobs(self):
        """Test case for fast_stats_jobs_get_fast_stats_jobs

        EXPERIMENTAL: Requires OrbitAdmin: Gets all the jobs in the FastStats job queue for all systems in a particular DataView.  # noqa: E501
        """
        pass

    def test_fast_stats_jobs_get_fast_stats_jobs_for_system(self):
        """Test case for fast_stats_jobs_get_fast_stats_jobs_for_system

        EXPERIMENTAL: Requires OrbitAdmin: Gets all the jobs in the FastStats job queue for the given system.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
