# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import apteco_api
from apteco_api.models.people_stage_lookup import PeopleStageLookup  # noqa: E501
from apteco_api.rest import ApiException

class TestPeopleStageLookup(unittest.TestCase):
    """PeopleStageLookup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PeopleStageLookup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = apteco_api.models.people_stage_lookup.PeopleStageLookup()  # noqa: E501
        if include_optional :
            return PeopleStageLookup(
                people_stage_elements_lookup = [
                    apteco_api.models.element_summary.ElementSummary(
                        id = '0', 
                        description = '0', 
                        type = 'Unknown', 
                        schema_id = 56, 
                        schema_id_type = 'Unknown', 
                        parent_id = '0', 
                        parent_type = 'Unknown', 
                        path = [
                            apteco_api.models.element_key.ElementKey(
                                id = '0', 
                                description = '0', )
                            ], )
                    ]
            )
        else :
            return PeopleStageLookup(
                people_stage_elements_lookup = [
                    apteco_api.models.element_summary.ElementSummary(
                        id = '0', 
                        description = '0', 
                        type = 'Unknown', 
                        schema_id = 56, 
                        schema_id_type = 'Unknown', 
                        parent_id = '0', 
                        parent_type = 'Unknown', 
                        path = [
                            apteco_api.models.element_key.ElementKey(
                                id = '0', 
                                description = '0', )
                            ], )
                    ],
        )

    def testPeopleStageLookup(self):
        """Test PeopleStageLookup"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
