# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import apteco_api
from apteco_api.api.audience_settings_api import AudienceSettingsApi  # noqa: E501
from apteco_api.rest import ApiException


class TestAudienceSettingsApi(unittest.TestCase):
    """AudienceSettingsApi unit test stubs"""

    def setUp(self):
        self.api = apteco_api.api.audience_settings_api.AudienceSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_audience_settings_get_audience_settings_for_system(self):
        """Test case for audience_settings_get_audience_settings_for_system

        SUBJECT TO CHANGE OR REMOVAL WITHOUT NOTICE: Returns some top-level settings for the specified FastStats system available for use with audiences  # noqa: E501
        """
        pass

    def test_audience_settings_get_audience_settings_for_systems(self):
        """Test case for audience_settings_get_audience_settings_for_systems

        SUBJECT TO CHANGE OR REMOVAL WITHOUT NOTICE: Returns the list of FastStats systems available for using audiences  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
