packageName: "apteco_api"
projectName: "apteco-api"
packageVersion: "0.3.0"
ignoreFileOverride: "pkg/.openapi-generator-ignore"
#packageUrl: null
#sortParamsByRequiredFlag: true
#hideGenerationTimestamp: true
#generateSourceCodeOnly: false
#library: "urllib3"