packageName: "apteco_api"
projectName: "apteco-api"
packageVersion: "0.2.4"
#packageUrl: null
#sortParamsByRequiredFlag: true
#hideGenerationTimestamp: true
#generateSourceCodeOnly: false
#library: "urllib3"