packageName: "apteco_api"
projectName: "apteco-api"
packageVersion:	"0.1.4"
#packageUrl: null
#sortParamsByRequiredFlag: true
#hideGenerationTimestamp: true
#generateSourceCodeOnly: false
#library: "urllib3"