# coding: utf-8

"""
    Apteco API

    An API to allow access to Apteco Marketing Suite resources  # noqa: E501

    The version of the OpenAPI document: v2
    Contact: support@apteco.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from apteco_api.configuration import Configuration


class TextVariableInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'maximum_text_length': 'int'
    }

    attribute_map = {
        'maximum_text_length': 'maximumTextLength'
    }

    def __init__(self, maximum_text_length=None, local_vars_configuration=None):  # noqa: E501
        """TextVariableInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._maximum_text_length = None
        self.discriminator = None

        if maximum_text_length is not None:
            self.maximum_text_length = maximum_text_length

    @property
    def maximum_text_length(self):
        """Gets the maximum_text_length of this TextVariableInfo.  # noqa: E501

        The maximum length of text data (in bytes) that can be held in the variable per record  # noqa: E501

        :return: The maximum_text_length of this TextVariableInfo.  # noqa: E501
        :rtype: int
        """
        return self._maximum_text_length

    @maximum_text_length.setter
    def maximum_text_length(self, maximum_text_length):
        """Sets the maximum_text_length of this TextVariableInfo.

        The maximum length of text data (in bytes) that can be held in the variable per record  # noqa: E501

        :param maximum_text_length: The maximum_text_length of this TextVariableInfo.  # noqa: E501
        :type: int
        """

        self._maximum_text_length = maximum_text_length

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TextVariableInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TextVariableInfo):
            return True

        return self.to_dict() != other.to_dict()
